### ISSUE TITLE
NullPointerException when trying to create a new mod

### ISSUE THREAD

**Issue by rubikscraft** [ExtraCrafTX/GeneratorFabricMod#11]
It gives this:

```
Outputting .gitignore [done] 1ms
Outputting settings.gradle [done] 0ms
Outputting gradlew [done] 1ms
Outputting gradlew.bat [done] 0ms
Outputting gradle/wrapper/gradle-wrapper.jar [done] 1ms
Outputting gradle/wrapper/gradle-wrapper.properties [done] 0ms
Outputting gradle.properties [done] 58ms
Outputting build.gradle [done] 9ms
Outputting src/main/java/nl/rubikscraft/minecraft/easymcmp/Main.java [done] 18ms
Outputting src/main/resources/assets/easymcmp/icon.png [done] 1ms
java.lang.NullPointerException
        at com.extracraftx.minecraft.templatemakerfabric.TemplateMakerFabric.outputFabricModJson(TemplateMakerFabric.java:89)
        at com.extracraftx.minecraft.templatemakerfabric.TemplateMakerFabric.outputMod(TemplateMakerFabric.java:69)
        at com.extracraftx.minecraft.generatorfabricmod.GeneratorFabricMod.main(GeneratorFabricMod.java:214)
```

**Comment by isuckatprogram** [comment]
Minecraft is cool
