### ISSUE TITLE
NPE when attempting to display list of MC versions to select

### ISSUE THREAD

**Issue by iconmaster5326** [ExtraCrafTX/GeneratorFabricMod#12]
* OS: Windows
* Shell: PowerShell
* JDK: 1.8.0_221

When I attempt to run this program, it crashes the first time it displays a choice menu:

```
PS GeneratorFabricMod> .\gradlew.bat run                                               
> Task :run
May 31, 2020 9:40:33 AM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Getting Minecraft versions... [done] 637ms
Getting Fabric API versions... [done] 314ms
Getting Yarn mapping versions... [done] 253ms
Getting Loom versions... [done] 301ms
Getting Fabric Loader versions... [done] 180ms
    Minecraft version:
  20w06a
> 1.15.2
  1.15.2-pre2
  1.15.2-pre1
  1.15.1
  1.15.1-pre1
  1.15
(Move to reveal additional choices)
java.lang.NullPointerException
        at com.extracraftx.minecraft.generatorfabricmod.terminal.Interface$Prompter.scrollingList(Interface.java:687)
        at com.extracraftx.minecraft.generatorfabricmod.terminal.Interface$Prompter.promptList(Interface.java:618)
        at com.extracraftx.minecraft.generatorfabricmod.terminal.Interface.promptList(Interface.java:120)
        at com.extracraftx.minecraft.generatorfabricmod.GeneratorFabricMod.main(GeneratorFabricMod.java:88)

BUILD SUCCESSFUL in 5s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by ExtraCrafTX** [comment]
Could you try the latest version (0.1.3) and let me know if that solves the issue? Thanks.

**Comment by ExtraCrafTX** [comment]
Closing, please open another issue if the problem has persisted.
