### ISSUE TITLE
Server returned HTTP response code: 500 for URL.

### ISSUE THREAD

**Issue by ghost** [ExtraCrafTX/GeneratorFabricMod#22]
```
🐧# ./GeneratorFabricMod 
GeneratorFabricMod version 0.1.4
Getting Minecraft versions... [done] 530ms
Getting Fabric API versions... [done] 457ms
Getting Yarn mapping versions... [done] 210ms
Getting Loom versions... [=   ]java.io.IOException: Server returned HTTP response code: 500 for URL: https://maven.fabricmc.net/net/fabricmc/fabric-loom/maven-metadata.xml
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.xmlFromUrl(DataProvider.java:269)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.getLoomVersions(DataProvider.java:198)
        at com.extracraftx.minecraft.generatorfabricmod.GeneratorFabricMod.main(GeneratorFabricMod.java:74)
```
Looks like the site returns nothing cuz there's no such thing as "https://maven.fabricmc.net/net/fabricmc/fabric-loom/maven-metadata.xml"

**Comment by ExtraCrafTX** [comment]
The URL currently takes me to the right file, maybe it was down for a short while. Can you give it another shot?

**Comment by ghost** [comment]
Now its fine, but i cant build it due to gradlew.settings.
