### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by redstoneguy12** [ExtraCrafTX/GeneratorFabricMod#7]
When I try to launch it, I get the following error:

```
Exception in thread "main" java.io.IOError: java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at org.jline.utils.Curses.tputs(Curses.java:62)
	at org.jline.utils.Curses.tputs(Curses.java:45)
	at org.jline.keymap.KeyMap.key(KeyMap.java:243)
	at org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:6095)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:6103)
	at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5813)
	at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5789)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:293)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
	at com.extracraftx.minecraft.generatorfabricmod.terminal.Interface.<init>(Interface.java:40)
	at com.extracraftx.minecraft.generatorfabricmod.GeneratorFabricMod.main(GeneratorFabricMod.java:49)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.String.charAt(String.java:658)
	at org.jline.utils.Curses.doTputs(Curses.java:359)
	at org.jline.utils.Curses.tputs(Curses.java:60)
	... 19 more
```

This happens on 0.1.2 with java 11 and 0.1.1 with java 8. My OS is Arch Linux.

**Comment by ExtraCrafTX** [comment]
Are you using an unconventional terminal or shell? I can't seem to reproduce this at all.

**Comment by redstoneguy12** [comment]
Well I was using ZSH, but I just tested and it happens in bash too. The terminal is just URXVT

**Comment by atk91** [comment]
Just ran into same issue with `scala`
`TERM=rxvt-unicode-256color scala`

**Comment by atk91** [comment]
They fixed it, so you need to bump `jline` version when it will be released.

**Comment by ExtraCrafTX** [comment]
Thanks.
